version: '3'
services:
 rabbitmq:
  image: rabbitmq:3-management
  network_mode: "host"
  restart: always
  ports:
    - 5672:5672
    - 15672:15672
 consumer:
  build: consumer
  network_mode: "host"
  restart: on-failure
  depends_on:
    - rabbitmq

 db:
  image: postgres
  restart: on-failure
  network_mode: "host"
  environment:
    POSTGRES_PASSWORD: az;.1029
  volumes:
    - ./postgresdata:/var/lib/postgresql/data


 app:
  build: app
  network_mode: "host"
  restart: on-failure
  environment:
    DATABASE_URL: "postgresql://postgres:az;.1029@localhost/postgres"
  ports:
    - 5000:5000
  depends_on: 
    - rabbitmq

 
